export enum Medos {
  TALASSOFOBIA = 'talassofobia',
  ARACNOFOBIA = 'aracnofobia',
  OFIDIOFOBIA = 'ofidiofobia',
  ACROFOBIA = 'acrofobia',
  AGORAFOBIA = 'agorafobia',
  CLAUSTROFOBIA = 'claustrofobia',
  AEROFOBIA = 'aerofobia',
  TRIPOFOBIA = 'tripofobia',
  MISOFOBIA = 'misofobia',
  NICTOFOBIA = 'nictofobia',
  HEMOFOBIA = 'hemofbobia',
  CINOFOBIA = 'cinofoia',
  TANATOFOBIA = 'tanatofobia',
}
